# This is a basic workflow to help you get started with Actions

name: Github Actions Maven

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v3

      # Use JDK 17
      - name: Step 2 - Set up JDK 17 
        uses: actions/setup-java@v3.4.0
        with:
          java-version: 17
          distribution: zulu

      # Builds the project
      - name: Step 3 - Build Maven Project
        run: mvn -B package --file pom.xml
        
      # Upload the Project
      - name: Step 4 - Upload the Project
        uses: actions/upload-artifact@v3.1.0
        with:
          name: TestRepo Upload
          path: target/*.jar
  
  publish:
    needs: build
    runs-on: ubuntu-latest
      
    steps:
      - name: create 
        uses: actions/checkout@v3
      # Use JDK 17
      - name: Step 2 - Set up JDK 17 
        uses: actions/setup-java@v3.4.0
        with:
          java-version: 17
          distribution: zulu

      - name: Update version
        run: mvn -B versions:set -DnewVersion=v${{github.run_number}} -DgenerateBackupPoms=false
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
     
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Download artifact
        uses: actions/download-artifact@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: yansto/testrepo:v${{github.run_number}}
