name: Build and Push docker image to Docker Hub
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build package
        run: mvn --batch-mode package --file pom.xml
        #  env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create artifacts directory and copy war file
        #  run: mkdir artifacts && cp target/*.war artifacts

        uses: actions/upload-artifact@v2
        with:
          name: test-1.0-SNAPSHOT.jar
          path: target/test-1.0-SNAPSHOT.jar


  Publish:
    needs: Build
    runs-on: ubuntu-latest
    steps:Create
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Update version
      run: mvn -B versions:set -DnewVersion=v${{github.run_number}} -DgenerateBackupPoms=false
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2.0.0
      with:
        username: yansto
        password: f1bdb298-664b-4c95-9886-ba6ae8fdeabb

    - name: Download artifact
      uses: actions/download-artifact@v2

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: saranitact/repo1:v${{github.run_number}}